### ISSUE TITLE
TypeError: o is not a function

### ISSUE THREAD

**Issue by ArciAndres** [sasza2/react-panzoom#106]
Hi! First of all, I would like to thank you for this development. Very nice.

I am trying to integrate it within an app, but I am getting the following error:

```
ERROR
o is not a function
TypeError: o is not a function
    at d.onload (http://localhost:3000/static/js/bundle.js:43337:68)
```

I created a light example repo where I see the problem:
https://github.com/ArciAndres/panzoom

Run with `npm start`.

I downgraded to version 1.6.5 and the problem disappears.
I think that the app breaks with this commit when passing to version 1.7.0: 03fd2df518d7eae9ac20d5447b3c3aa7d0b72602

On a side note, I downloaded the repo and tried to run `npm run dev`, and encountered another error. May or may not be related.

```
7:40:07 AM [vite] Internal server error: Missing "./react/jsx-dev-runtime" specifier in "@sasza/react-panzoom" package
  Plugin: vite:import-analysis
  File: D:/Others/LingoStonks/Others/react-panzoom/src/stories/Api.stories.tsx
      at e (file:///D:/Others/LingoStonks/Others/react-panzoom/node_modules/.pnpm/vite@4.2.1/node_modules/vite/dist/node/chunks/dep-79892de8.js:16076:25)
      at n (file:///D:/Others/LingoStonks/Others/react-panzoom/node_modules/.pnpm/vite@4.2.1/node_modules/vite/dist/node/chunks/dep-79892de8.js:16076:627)
      at o (file:///D:/Others/LingoStonks/Others/react-panzoom/node_modules/.pnpm/vite@4.2.1/node_modules/vite/dist/node/chunks/dep-79892de8.js:16076:1297)
      at resolveExportsOrImports (file:///D:/Others/LingoStonks/Others/react-panzoom/node_modules/.pnpm/vite@4.2.1/node_modules/vite/dist/node/chunks/dep-79892de8.js:23295:20)
      at resolveDeepImport (file:///D:/Others/LingoStonks/Others/react-panzoom/node_modules/.pnpm/vite@4.2.1/node_modules/vite/dist/node/chunks/dep-79892de8.js:23314:31)
      at tryNodeResolve (file:///D:/Others/LingoStonks/Others/react-panzoom/node_modules/.pnpm/vite@4.2.1/node_modules/vite/dist/node/chunks/dep-79892de8.js:23000:20)
      at Context.resolveId (file:///D:/Others/LingoStonks/Others/react-panzoom/node_modules/.pnpm/vite@4.2.1/node_modules/vite/dist/node/chunks/dep-79892de8.js:22762:28)
      at async Object.resolveId (file:///D:/Others/LingoStonks/Others/react-panzoom/node_modules/.pnpm/vite@4.2.1/node_modules/vite/dist/node/chunks/dep-79892de8.js:43314:32)
      at async Context.resolve (file:///D:/Others/LingoStonks/Others/react-panzoom/node_modules/.pnpm/vite@4.2.1/node_modules/vite/dist/node/chunks/dep-79892de8.js:43043:23)
      at async viteResolve (file:///D:/Others/LingoStonks/Others/react-panzoom/node_modules/.pnpm/vite-tsconfig-paths@3.6.0_vite@4.2.1/node_modules/vite-tsconfig-paths/dist/index.mjs:78:24)
      at async file:///D:/Others/LingoStonks/Others/react-panzoom/node_modules/.pnpm/vite-tsconfig-paths@3.6.0_vite@4.2.1/node_modules/vite-tsconfig-paths/dist/index.mjs:152:17
      at async Context.resolveId (file:///D:/Others/LingoStonks/Others/react-panzoom/node_modules/.pnpm/vite-tsconfig-paths@3.6.0_vite@4.2.1/node_modules/vite-tsconfig-paths/dist/index.mjs:81:28)
      at async Object.resolveId (file:///D:/Others/LingoStonks/Others/react-panzoom/node_modules/.pnpm/vite@4.2.1/node_modules/vite/dist/node/chunks/dep-79892de8.js:43314:32)
      at async TransformContext.resolve (file:///D:/Others/LingoStonks/Others/react-panzoom/node_modules/.pnpm/vite@4.2.1/node_modules/vite/dist/node/chunks/dep-79892de8.js:43043:23)
      at async normalizeUrl (file:///D:/Others/LingoStonks/Others/react-panzoom/node_modules/.pnpm/vite@4.2.1/node_modules/vite/dist/node/chunks/dep-79892de8.js:41370:34)
      at async TransformContext.transform (file:///D:/Others/LingoStonks/Others/react-panzoom/node_modules/.pnpm/vite@4.2.1/node_modules/vite/dist/node/chunks/dep-79892de8.js:41512:47)
      at async Object.transform (file:///D:/Others/LingoStonks/Others/react-panzoom/node_modules/.pnpm/vite@4.2.1/node_modules/vite/dist/node/chunks/dep-79892de8.js:43387:30)
      at async loadAndTransform (file:///D:/Others/LingoStonks/Others/react-panzoom/node_modules/.pnpm/vite@4.2.1/node_modules/vite/dist/node/chunks/dep-79892de8.js:41105:29)
```

Thank you in advance for any help!

**Comment by sasza2** [comment]
hi, thanks! I just fixed this issue. please, try version 1.8.9 

to run development mode try: `pnpm dev` with some newer version of Node

**Comment by ArciAndres** [comment]
I tried the updated and the error disappeared, and works as expected. The second error is still present, but not part of this issue apparently.

Thank you!
